package dc10.scala.internal

import dc10.scala.*

object indentation:

  extension (statement: Statement)
    def addIndent: Statement =
      statement match
        case s@CaseDef(lambda) => s
        case s@CaseClassDef(tpe, _, _) => s.copy(tpe = tpe.copy(lvl = tpe.lvl + 1))
        case s@LibDep(_, _, _) => s
        case s@PackageDef(_, _) => s
        case s@`DefDef: x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`DefDef: x_x x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`DefDef: x_x_x x x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@ObjDef(obj) => s.copy(obj = obj.copy(lvl = obj.lvl + 1, body = obj.body.map(s => s.addIndent)))
        case s@`SealedTraitDef: x`(tpe) => s.copy(tpe = tpe.copy(lvl = tpe.lvl + 1))
        case s@`TraitDef: x`(tpe) => s.copy(tpe = tpe.copy(lvl = tpe.lvl + 1))
        case s@`TraitDef: x_x`(tpe, _, body) => s.copy(tpe = tpe.copy(lvl = tpe.lvl + 1), body = s.body.map(s => s.addIndent))
        case s@`TypeDef: x`(tpe) => s.copy(tpe = tpe.copy(lvl = tpe.lvl + 1))
        case s@`TypeDef: x_x x`(tpe) => s.copy(tpe = tpe.copy(lvl = tpe.lvl + 1))
        case s@`ValDef: x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: x_x x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: x_x llx_xl_x_x x_x xl`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: x_x_x x x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: x_x_x x llx_xl_x_x x_x xl`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: x_x_x x lx_x llx_xl_x_x x_x xll`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: lx_xl_x_x x_x x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: lx_xl_x_x x_x llx_xl_x x_xl`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`GivenDef: x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`GivenDef: x_x x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
      
  extension (tpe: Type)
    def addIndent: Type =
      tpe match
        case t@`Type.Lit: x`(lvl, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: x_x x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: x_x x`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: lx_xl_x x_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: lx_xl_x x_x`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: lx_x_xl_x x_x_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: lx_x_xl_x x_x_x`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: llx_xl_xl_x lx_xl_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: llx_xl_xl_x lx_xl_x`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: llx_xl_x_xl_x lx_xl_x_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: llx_xl_x_xl_x lx_xl_x_x`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: x_x_x x x`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x_x_x x x`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: x_x_x x x`(lvl, _, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x_x_x x lx_x xl`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x_x_x x llx_xl_x_x x_x xl`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x_x_x x llx_xl_x_x x_xl`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: lx_xl_x_x x_x x`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: lx_xl_x_x x_x x`(lvl, _, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x_x_x lx_x xl llx_xl_x_x x_x xl`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        // case t@`Type.App: x_x_x_x x * x`(lvl, tfun, aarg, barg, carg) => t.copy(lvl = lvl + 1)
        // case t@`Type.AppInfix: x_x_x_x x * x`(lvl, tfun, aarg, barg, carg) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: x_x_x_x x * x`(lvl, sym, aarg, barg, carg, impl) => t.copy(lvl = lvl + 1)
        // case t@`Type.App: lx_xl_x_x_x lx_xl x x`(lvl, tfun, farg, aarg, barg) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: lx_xl_x_x_x lx_xl x x`(lvl, sym, farg, aarg, barg, impl) => t.copy(lvl = lvl + 1)
        // case t@`Type.App: x_x_x_x_x x * x x`(lvl, tfun, aarg, barg, carg, darg) => t.copy(lvl = lvl + 1)
        // case t@`Type.AppInfix: x_x_x_x_x x * x x`(lvl, tfun, aarg, barg, carg, darg) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: x_x_x_x_x x * x x`(lvl, sym, aarg, barg, carg, darg, impl) => t.copy(lvl = lvl + 1)
        // case t@`Type.App: lx_xl_x_x_x_x lx_xl x * x`(lvl, tfun, farg, aarg, barg, carg) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: lx_xl_x_x_x_x lx_xl x * x`(lvl, sym, farg, aarg, barg, carg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: x_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: x_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: lx_xl_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: lx_xl_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: lx_x_xl_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: lx_x_xl_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: llx_xl_x_xl_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: llx_xl_x_xl_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: x_x_x`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: x_x_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: lx_xl_x_x`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: lx_xl_x_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        // case t@`Type.Lam: x_x_x_x`(lvl, domain1, domain2, domain3, codomain) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: x_x_x_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        // case t@`Type.Lam: lx_xl_x_x_x`(lvl, domain1, domain2, domain3, codomain) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: lx_xl_x_x_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        // case t@`Type.Lam: x_x_x_x_x`(lvl, domain1, domain2, domain3, domain4, codomain) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: x_x_x_x_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        // case t@`Type.Lam: lx_xl_x_x_x_x`(lvl, _, _, _, _, _) =>  t.copy(lvl = lvl + 1)
        // case t@`Type.Var: lx_xl_x_x_x_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: llx_xl_xl_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: llx_xl_xl_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: lx_xl_x_x x_x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: lx_xl_x_x x_x`(lvl, _, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x_x_x x lx_x llx_xl_x_x x_x xll`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: x_x llx_xl_x_x x_x xl`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: lx_xl_x_x x_x llx_xl_x x_xl`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: lx_xl_x_x x_x llx_xl_x_x x_x xl`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x_x_x llx_xl_x_x x_x xl llx_xl_x_x x_x llx_xl_x x_xll`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x_x_x llx_xl_x_x x_x xl llx_xl_x_x x_x llx_xl_x_x x_x xll`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x_x_x lx_x llx_xl_x_x x_x xll llx_xl_x_x x_x llx_xl_x_x x_x xll`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x_x_x lx_x_x llx_xl_x_x x_x xl llx_xl_x_x x_x llx_xl_x x_xlll llx_xl_x_x x_x llx_xl_x x_xll`(lvl, _, _, _) => t.copy(lvl = lvl + 1)

  extension (value: Value)
    def addIndent: Value =
      value match
        case v@`Value.App.0: x_x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.App.0: lx_xl_x_x`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        // case v@`Value.App.0: lx_xl_x_x_x`(lvl, fun, targf, targa, targb, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: x_x x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: lx_xl_x_x x_x x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: lx_xl_x_x x_x`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        // case v@`Value.App.2: x`(lvl, fun, arg1, arg2, tpe) => v.copy(lvl = lvl + 1)
        // case v@`Value.App.3: x`(lvl, fun, arg1, arg2, arg3, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.0: x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.0: lx_xl_x_x x_x x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.0: lx_xl_x_x x_x`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.1: x`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDotless: x`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        case `Value.App.Vargs: x`(lvl, fun, tpe, vargs*) => `Value.App.Vargs: x`(lvl + 1, fun, tpe, vargs*)
        case v@`Value.AppDot.1: x_x x`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.1: x_x llx_xl_x_x x_x xl`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.1: lx_xl_x_x x_x x`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.1: lx_xl_x_x x_x llx_xl_x x_xl`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.1_: lx_xl_x_x x_x llx_xl_x x_xl`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.AppForComp: x_x x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.0: x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: x_x_x x x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Boolean: x`(lvl, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Int: x`(lvl, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Long: x`(lvl, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Float: x`(lvl, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Double: x`(lvl, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.String: x`(lvl, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Unit: x`(lvl, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Obj: x`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1, body = v.body.map(s => s.addIndent))
        case v@`Value.Lam.1: x_x_x x x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Lam1: x_x_x llx_xl_x_x x_x xl llx_xl_x_x x_x llx_xl_x x_xll`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x_x_x x x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x_x_x x llx_xl_x_x x_x xl`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x_x_x x llx_xl_x_x x_xl`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x_x_x x lx_x llx_xl_x_x x_x xll`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x_x_x llx_xl_x_x x_x xl llx_xl_x_x x_x llx_xl_x x_xll`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        // case v@`Value.Lam.2: x_x_x_x x * x`(lvl, a1, a2, r, tpe) => v.copy(lvl = lvl + 1)
        // case v@`Value.Lam.3: x_x_x_x_x x * x x`(lvl, a1, a2, a3, r, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: lx_xl_x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x_x x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: lx_xl_x_x x_x x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x_x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: lx_xl_x_x x_x`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x_x_x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: lx_xl_x_x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x_x llx_xl_x_x x_x xl`(lvl, _, _, _) =>  v.copy(lvl = lvl + 1)
        case v@`Value.Val: lx_xl_x x_x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: lx_xl_x_x x_x llx_xl_x x_xl`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: lx_xl_x_x x_x llx_xl_x_x x_x xl`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        // case v@`Value.Val: lx_xl_x_x_x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.0: x_x x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: x_x_x x lx_x xl`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: x_x_x x llx_xl_x_x x_x xl`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: x_x_x x lx_x llx_xl_x_x x_x xll`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.0: x_x_x lx_x xl llx_xl_x_x x_x xl`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: x_x_x llx_xl_x_x x_x xl llx_xl_x_x x_x llx_xl_x x_xll`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: lx_xl_x_x x_x llx_xl_x x_xl`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.0: x_x_x lx_x llx_xl_x_x x_x xll llx_xl_x_x x_x llx_xl_x_x x_x xll`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.0: lx_xl_x_x x_x llx_xl_x_x x_x xl`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        // case v@`Value.Def.1: x_x_x llx_xl_x_x x_x xl llx_xl_x_x x_x llx_xl_x_x x_x xll`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        // case v@`Value.Lam1: x_x_x llx_xl_x_x x_x xl llx_xl_x_x x_x llx_xl_x_x x_x xll`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        // case v@`Value.Val: x_x_x llx_xl_x_x x_x xl llx_xl_x_x x_x llx_xl_x_x x_x xll`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: x_x_x lx_x_x llx_xl_x_x x_x xl llx_xl_x_x x_x llx_xl_x x_xlll llx_xl_x_x x_x llx_xl_x x_xll`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Giv: x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Giv: x_x x`(lvl, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.List: x_x x`(lvl, _, _) => v.copy(lvl = lvl + 1)