package dc10.scala.internal

import dc10.scala.*

object indentation:

  extension (statement: Statement)
    def addIndent: Statement =
      statement match
        case s@CaseDef(lambda) => s
        case s@CaseClassDef(tpe, fields, body) => s.copy(tpe = tpe.copy(lvl = tpe.lvl + 1))
        case s@LibDep(org, nme, ver) => s
        case s@PackageDef(nme, contents) => s
        case s@`DefDef: *`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`DefDef: *→* *`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`DefDef: *→*→* * *`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@ObjDef(obj) => s.copy(obj = obj.copy(lvl = obj.lvl + 1, body = obj.body.map(s => s.addIndent)))
        case s@`TypeDef: *`(tpe) => s.copy(tpe = tpe.copy(lvl = tpe.lvl + 1))
        case s@`TypeDef: *→* *`(tpe) => s.copy(tpe = tpe.copy(lvl = tpe.lvl + 1))
        case s@`ValDef: *`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: *→* *`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: *→* ((*→*)→*→* *→* *)`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: *→*→* * *`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: *→*→* * ((*→*)→*→* *→* *)`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: *→*→* * (*→* ((*→*)→*→* *→* *))`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: (*→*)→*→* *→* *`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
      
  extension (tpe: Type)
    def addIndent: Type =
      tpe match
        case t@`Type.Lit: *`(lvl, nme) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: *`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: *→* *`(lvl, tfun, aarg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: *→* *`(lvl, sym, aarg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: (*→*)→* *→*`(lvl, tfun, farg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (*→*)→* *→*`(lvl, sym, farg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: (*→*→*)→* *→*→*`(lvl, tfun, farg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (*→*→*)→* *→*→*`(lvl, sym, farg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: ((*→*)→*)→* (*→*)→*`(lvl, tfun, farg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: ((*→*)→*)→* (*→*)→*`(lvl, sym, farg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: ((*→*)→*→*)→* (*→*)→*→*`(lvl, tfun, farg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: ((*→*)→*→*)→* (*→*)→*→*`(lvl, sym, farg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: *→*→* * *`(lvl, tfun, aarg, barg) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: *→*→* * *`(lvl, tfun, aarg, barg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: *→*→* * *`(lvl, sym, aarg, barg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: *→*→* * (*→* *)`(lvl, tfun, aarg, barg) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: *→*→* * ((*→*)→*→* *→* *)`(lvl, tfun, aarg, barg) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: *→*→* * ((*→*)→*→* *→*)`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: (*→*)→*→* *→* *`(lvl, tfun, farg, aarg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (*→*)→*→* *→* *`(lvl, sym, farg, aarg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: *→*→* (*→* *) ((*→*)→*→* *→* *)`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: *→*→*→* * * *`(lvl, tfun, aarg, barg, carg) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: *→*→*→* * * *`(lvl, tfun, aarg, barg, carg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: *→*→*→* * * *`(lvl, sym, aarg, barg, carg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: (*→*)→*→*→* (*→*) * *`(lvl, tfun, farg, aarg, barg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (*→*)→*→*→* (*→*) * *`(lvl, sym, farg, aarg, barg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: *→*→*→*→* * * * *`(lvl, tfun, aarg, barg, carg, darg) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: *→*→*→*→* * * * *`(lvl, tfun, aarg, barg, carg, darg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: *→*→*→*→* * * * *`(lvl, sym, aarg, barg, carg, darg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: (*→*)→*→*→*→* (*→*) * * *`(lvl, tfun, farg, aarg, barg, carg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (*→*)→*→*→*→* (*→*) * * *`(lvl, sym, farg, aarg, barg, carg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: *→*`(lvl, domain, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: *→*`(lvl, sym, impl, ctors) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: (*→*)→*`(lvl, domain, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (*→*)→*`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: (*→*→*)→*`(lvl, domain, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (*→*→*)→*`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: ((*→*)→*→*)→*`(lvl, domain, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: ((*→*)→*→*)→*`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: *→*→*`(lvl, domain1, domain2, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: *→*→*`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: (*→*)→*→*`(lvl, domain1, domain2, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (*→*)→*→*`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: *→*→*→*`(lvl, domain1, domain2, domain3, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: *→*→*→*`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: (*→*)→*→*→*`(lvl, domain1, domain2, domain3, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (*→*)→*→*→*`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: *→*→*→*→*`(lvl, domain1, domain2, domain3, domain4, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: *→*→*→*→*`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: (*→*)→*→*→*→*`(lvl, _, _, _, _, _) =>  t.copy(lvl = lvl + 1)
        case t@`Type.Var: (*→*)→*→*→*→*`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: ((*→*)→*)→*`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: ((*→*)→*)→*`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: (*→*)→*→* *→*`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (*→*)→*→* *→*`(lvl, _, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: *→*→* * (*→* ((*→*)→*→* *→* *))`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: *→* ((*→*)→*→* *→* *)`(lvl, _, _) => t.copy(lvl = lvl + 1)

  extension (value: Value)
    def addIndent: Value =
      value match
        case v@`Value.App.0: *→*`(lvl, fun, targ, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.App.0: (*→*)→*→*`(lvl, fun, targf, targa, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.App.0: (*→*)→*→*→*`(lvl, fun, targf, targa, targb, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: *`(lvl, fun, arg, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: *→* *`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: (*→*)→*→* *→* *`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: (*→*)→*→* *→*`(lvl, sym, targ, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.App.2: *`(lvl, fun, arg1, arg2, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.App.3: *`(lvl, fun, arg1, arg2, arg3, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.0: *`(lvl, fun, arg1, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.0: (*→*)→*→* *→* *`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.0: (*→*)→*→* *→*`(lvl, sym, targ, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.1: *`(lvl, fun, arg1, arg2, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDotless: *`(lvl, fun, arg1, arg2, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.App.Vargs: *`(lvl, fun, tpe, vargs*) => `Value.App.Vargs: *`(lvl + 1, fun, tpe, vargs*)
        case v@`Value.AppDot.1: *→* *`(lvl, sym, targ, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.1: *→* ((*→*)→*→* *→* *)`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.1: (*→*)→*→* *→* *`(lvl, sym, targ, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.AppForComp: *→* *`(lvl, gens, ret, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.0: *`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: *→*→* * *`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Boolean: *`(lvl, tpe, b) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Int: *`(lvl, tpe, i) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Long: *`(lvl, tpe, l) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Float: *`(lvl, tpe, f) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Double: *`(lvl, tpe, d) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.String: *`(lvl, tpe, s) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Unit: *`(lvl, tpe, u) => v.copy(lvl = lvl + 1)
        case v@`Value.Obj: *`(lvl, sym, tpe, parent, body) => v.copy(lvl = lvl + 1, body = v.body.map(s => s.addIndent))
        case v@`Value.Lam.1: *→*→* * *`(lvl, a, b, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: *→*→* * *`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: *→*→* * ((*→*)→*→* *→* *)`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: *→*→* * ((*→*)→*→* *→*)`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: *→*→* * (*→* ((*→*)→*→* *→* *))`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Lam.2: *→*→*→* * * *`(lvl, a1, a2, r, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.Lam.3: *→*→*→*→* * * * *`(lvl, a1, a2, a3, r, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: (*→*)→*`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: *`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: *→* *`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: (*→*)→*→* *→* *`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: *→*`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: (*→*)→*→* *→*`(lvl, sym, targ, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: *→*→*`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: (*→*)→*→*`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: (*→*)→*→*→*`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.0: *→* *`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: *→*→* * (*→* *)`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: *→*→* * ((*→*)→*→* *→* *)`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: *→*→* * (*→* ((*→*)→*→* *→* *))`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.0: *→*→* (*→* *) ((*→*)→*→* *→* *)`(lvl, sym, tpe, impl) =>  v.copy(lvl = lvl + 1)
        case v@`Value.Val: *→* ((*→*)→*→* *→* *)`(lvl, sym, tpe, impl) =>  v.copy(lvl = lvl + 1)