package dc10.scala.internal

import dc10.scala.*

object indentation:

  extension (statement: Statement)
    def addIndent: Statement =
      statement match
        case s@CaseDef(lambda) => s
        case s@CaseClassDef(tpe, fields, body) => s.copy(tpe = tpe.copy(lvl = tpe.lvl + 1))
        case s@LibDep(org, nme, ver) => s
        case s@PackageDef(nme, contents) => s
        case s@`DefDef: x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`DefDef: x→x x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`DefDef: x→x→x x x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@ObjDef(obj) => s.copy(obj = obj.copy(lvl = obj.lvl + 1, body = obj.body.map(s => s.addIndent)))
        case s@`TypeDef: x`(tpe) => s.copy(tpe = tpe.copy(lvl = tpe.lvl + 1))
        case s@`TypeDef: x→x x`(tpe) => s.copy(tpe = tpe.copy(lvl = tpe.lvl + 1))
        case s@`ValDef: x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: x→x x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: x→x ((x→x)→x→x x→x x)`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: x→x→x x x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: x→x→x x ((x→x)→x→x x→x x)`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: x→x→x x (x→x ((x→x)→x→x x→x x))`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: (x→x)→x→x x→x x`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
        case s@`ValDef: (x→x)→x→x x→x ((x→x)→x x→x)`(value) => s.copy(value = value.copy(lvl = value.lvl + 1))
      
  extension (tpe: Type)
    def addIndent: Type =
      tpe match
        case t@`Type.Lit: x`(lvl, nme) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: x`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: x→x x`(lvl, tfun, aarg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: x→x x`(lvl, sym, aarg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: (x→x)→x x→x`(lvl, tfun, farg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (x→x)→x x→x`(lvl, sym, farg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: (x→x→x)→x x→x→x`(lvl, tfun, farg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (x→x→x)→x x→x→x`(lvl, sym, farg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: ((x→x)→x)→x (x→x)→x`(lvl, tfun, farg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: ((x→x)→x)→x (x→x)→x`(lvl, sym, farg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: ((x→x)→x→x)→x (x→x)→x→x`(lvl, tfun, farg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: ((x→x)→x→x)→x (x→x)→x→x`(lvl, sym, farg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.App: x→x→x x x`(lvl, tfun, aarg, barg) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x→x→x x x`(lvl, tfun, aarg, barg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: x→x→x x x`(lvl, sym, aarg, barg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x→x→x x (x→x x)`(lvl, tfun, aarg, barg) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x→x→x x ((x→x)→x→x x→x x)`(lvl, tfun, aarg, barg) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x→x→x x ((x→x)→x→x x→x)`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: (x→x)→x→x x→x x`(lvl, tfun, farg, aarg) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (x→x)→x→x x→x x`(lvl, sym, farg, aarg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x→x→x (x→x x) ((x→x)→x→x x→x x)`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        // case t@`Type.App: x→x→x→x x * x`(lvl, tfun, aarg, barg, carg) => t.copy(lvl = lvl + 1)
        // case t@`Type.AppInfix: x→x→x→x x * x`(lvl, tfun, aarg, barg, carg) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: x→x→x→x x * x`(lvl, sym, aarg, barg, carg, impl) => t.copy(lvl = lvl + 1)
        // case t@`Type.App: (x→x)→x→x→x (x→x) x x`(lvl, tfun, farg, aarg, barg) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: (x→x)→x→x→x (x→x) x x`(lvl, sym, farg, aarg, barg, impl) => t.copy(lvl = lvl + 1)
        // case t@`Type.App: x→x→x→x→x x * x x`(lvl, tfun, aarg, barg, carg, darg) => t.copy(lvl = lvl + 1)
        // case t@`Type.AppInfix: x→x→x→x→x x * x x`(lvl, tfun, aarg, barg, carg, darg) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: x→x→x→x→x x * x x`(lvl, sym, aarg, barg, carg, darg, impl) => t.copy(lvl = lvl + 1)
        // case t@`Type.App: (x→x)→x→x→x→x (x→x) x * x`(lvl, tfun, farg, aarg, barg, carg) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: (x→x)→x→x→x→x (x→x) x * x`(lvl, sym, farg, aarg, barg, carg, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: x→x`(lvl, domain, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: x→x`(lvl, sym, impl, ctors) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: (x→x)→x`(lvl, domain, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (x→x)→x`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: (x→x→x)→x`(lvl, domain, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (x→x→x)→x`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: ((x→x)→x→x)→x`(lvl, domain, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: ((x→x)→x→x)→x`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: x→x→x`(lvl, domain1, domain2, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: x→x→x`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: (x→x)→x→x`(lvl, domain1, domain2, codomain) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (x→x)→x→x`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        // case t@`Type.Lam: x→x→x→x`(lvl, domain1, domain2, domain3, codomain) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: x→x→x→x`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        // case t@`Type.Lam: (x→x)→x→x→x`(lvl, domain1, domain2, domain3, codomain) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: (x→x)→x→x→x`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        // case t@`Type.Lam: x→x→x→x→x`(lvl, domain1, domain2, domain3, domain4, codomain) => t.copy(lvl = lvl + 1)
        // case t@`Type.Var: x→x→x→x→x`(lvl, sym, impl) => t.copy(lvl = lvl + 1)
        // case t@`Type.Lam: (x→x)→x→x→x→x`(lvl, _, _, _, _, _) =>  t.copy(lvl = lvl + 1)
        // case t@`Type.Var: (x→x)→x→x→x→x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Lam: ((x→x)→x)→x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: ((x→x)→x)→x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: (x→x)→x→x x→x`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.Var: (x→x)→x→x x→x`(lvl, _, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.AppInfix: x→x→x x (x→x ((x→x)→x→x x→x x))`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: x→x ((x→x)→x→x x→x x)`(lvl, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: (x→x)→x→x x→x ((x→x)→x x→x)`(lvl, _, _, _) => t.copy(lvl = lvl + 1)
        case t@`Type.App: (x→x)→x→x x→x ((x→x)→x→x x→x x)`(lvl, _, _, _) => t.copy(lvl = lvl + 1)

  extension (value: Value)
    def addIndent: Value =
      value match
        case v@`Value.App.0: x→x`(lvl, fun, targ, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.App.0: (x→x)→x→x`(lvl, fun, targf, targa, tpe) => v.copy(lvl = lvl + 1)
        // case v@`Value.App.0: (x→x)→x→x→x`(lvl, fun, targf, targa, targb, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: x`(lvl, fun, arg, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: x→x x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: (x→x)→x→x x→x x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: (x→x)→x→x x→x`(lvl, sym, targ, tpe, impl) => v.copy(lvl = lvl + 1)
        // case v@`Value.App.2: x`(lvl, fun, arg1, arg2, tpe) => v.copy(lvl = lvl + 1)
        // case v@`Value.App.3: x`(lvl, fun, arg1, arg2, arg3, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.0: x`(lvl, fun, arg1, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.0: (x→x)→x→x x→x x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.0: (x→x)→x→x x→x`(lvl, sym, targ, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.1: x`(lvl, fun, arg1, arg2, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDotless: x`(lvl, fun, arg1, arg2, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.App.Vargs: x`(lvl, fun, tpe, vargs*) => `Value.App.Vargs: x`(lvl + 1, fun, tpe, vargs*)
        case v@`Value.AppDot.1: x→x x`(lvl, sym, targ, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.1: x→x ((x→x)→x→x x→x x)`(lvl, _, _, _, _) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.1: (x→x)→x→x x→x x`(lvl, sym, targ, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.AppDot.1: (x→x)→x→x x→x ((x→x)→x x→x)`(lvl, sym, targ, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.AppForComp: x→x x`(lvl, gens, ret, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.0: x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: x→x→x x x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Boolean: x`(lvl, tpe, b) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Int: x`(lvl, tpe, i) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Long: x`(lvl, tpe, l) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Float: x`(lvl, tpe, f) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Double: x`(lvl, tpe, d) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.String: x`(lvl, tpe, s) => v.copy(lvl = lvl + 1)
        case v@`Value.Lit.Unit: x`(lvl, tpe, u) => v.copy(lvl = lvl + 1)
        case v@`Value.Obj: x`(lvl, sym, tpe, parent, body) => v.copy(lvl = lvl + 1, body = v.body.map(s => s.addIndent))
        case v@`Value.Lam.1: x→x→x x x`(lvl, a, b, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.Lam1: x→x→x ((x→x)→x→x x→x x) ((x→x)→x→x x→x ((x→x)→x x→x))`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x→x→x x x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x→x→x x ((x→x)→x→x x→x x)`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x→x→x x ((x→x)→x→x x→x)`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x→x→x x (x→x ((x→x)→x→x x→x x))`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x→x→x ((x→x)→x→x x→x x) ((x→x)→x→x x→x ((x→x)→x x→x))`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        // case v@`Value.Lam.2: x→x→x→x x * x`(lvl, a1, a2, r, tpe) => v.copy(lvl = lvl + 1)
        // case v@`Value.Lam.3: x→x→x→x→x x * x x`(lvl, a1, a2, a3, r, tpe) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: (x→x)→x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x→x x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: (x→x)→x→x x→x x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x→x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: (x→x)→x→x x→x`(lvl, sym, targ, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x→x→x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: (x→x)→x→x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: x→x ((x→x)→x→x x→x x)`(lvl, sym, tpe, impl) =>  v.copy(lvl = lvl + 1)
        case v@`Value.Val: (x→x)→x x→x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: (x→x)→x→x x→x ((x→x)→x x→x)`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Val: (x→x)→x→x x→x ((x→x)→x→x x→x x)`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        // case v@`Value.Val: (x→x)→x→x→x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.0: x→x x`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: x→x→x x (x→x x)`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: x→x→x x ((x→x)→x→x x→x x)`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: x→x→x x (x→x ((x→x)→x→x x→x x))`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.0: x→x→x (x→x x) ((x→x)→x→x x→x x)`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.Def.1: x→x→x ((x→x)→x→x x→x x) ((x→x)→x→x x→x ((x→x)→x x→x))`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)
        case v@`Value.App.1: (x→x)→x→x x→x ((x→x)→x x→x)`(lvl, sym, tpe, impl) => v.copy(lvl = lvl + 1)